### PR TITLE
New sample with an e2e Kafka application

### PR DESCRIPTION
**Pull request by codependent**
This PR adds a new kafka-e2e sample, showing an e2e scenario with three microservices (two producers and one stream) that model a subset of a purchasing system.

The usage is documented in a README.adoc file.

@sobychacko could you have a look an tell me if it's alright?

### CODE REVIEW

**Comment by sobychacko** [comment]
Hi @codependent Thank you for this PR. A couple of suggestions. What do you think about renaming the module to `kafka-e2e-kotlin-sample`? We need to add this module to the `modules` section in the root pom of the repository. I think it will also be nice to include the usage of `kafkacat` in the readme for tailing the contents of the orders repo. 

When running the sample, I am getting an exception as below on the shipping-service:
```
org.apache.avro.AvroTypeException: Found kafka.e2e.shipping.OrderShippedEvent, expecting kafka.e2e.order.OrderCreatedEvent, missing required field customerId
	at org.apache.avro.io.ResolvingDecoder.doAction(ResolvingDecoder.java:292) ~[avro-1.8.2.jar!/:1.8.2]
	at org.apache.avro.io.parsing.Parser.advance(Parser.java:88) ~[avro-1.8.2.jar!/:1.8.2]
```
I think that is because the same topic `order` is used to receive both `OrderCreated` and `OrderShipped` events. I think we need to clean that up by introducing some logic in the code to identify this. Could you address that as well?

**Comment by codependent** [comment]
@sobychacko I'm making the changes you requested.

Regarding the exception in the shipping service, it's not happening in my case. However it's true that two messages get to the KStream, the original OrderCreatedEvent and, after publishing an OrderShippedEvent, this one gets to the KStream and is unmarshalled as a OrderCreatedEvent. In any case this is incorrect and I should filter out these messages.

In a native Kafka sample [I solved this using a KStream<Int, GenericRecord> instead of a kStream<Int, OrderCreatedEvent>](https://github.com/codependent/event-carried-state-transfer/blob/avro/kafka-shipping-service/src/main/kotlin/com/codependent/statetransfer/shipping/KafkaShippingApplication.kt#L64). I tried to replicate this in Spring Cloud Stream:

```
    @StreamListener
    @SendTo("output")
    fun process(@Input("input") input: KStream<Int, Customer>, @Input("order") orderEvent: KStream<Int, GenericRecord>): KStream<Int, OrderShippedEvent> {

        val serdeConfig = mapOf(
                AbstractKafkaAvroSerDeConfig.SCHEMA_REGISTRY_URL_CONFIG to "http://localhost:8081")

        val intSerde = Serdes.IntegerSerde()
        val customerSerde = SpecificAvroSerde<Customer>()
        customerSerde.configure(serdeConfig, false)
        val orderCreatedSerde = SpecificAvroSerde<OrderCreatedEvent>()
        orderCreatedSerde.configure(serdeConfig, false)
        val orderShippedSerde = SpecificAvroSerde<OrderShippedEvent>()
        orderShippedSerde.configure(serdeConfig, false)

        val stateStore: Materialized<Int, Customer, KeyValueStore<Bytes, ByteArray>> =
                Materialized.`as`<Int, Customer, KeyValueStore<Bytes, ByteArray>>("customer-store")
                        .withKeySerde(intSerde)
                        .withValueSerde(customerSerde)

        val customerTable: KTable<Int, Customer> = input.groupByKey(Serialized.with(intSerde, customerSerde))
                .reduce({ _, y -> y }, stateStore)

        return (orderEvent.filter { _, value -> value.schema.name == "OrderCreatedEvent" }
                .map { key, value -> KeyValue(key, OrderCreatedEvent(value.get("id") as Int, value.get("productId") as Int, value.get("customerId") as Int)) }
                .selectKey { _, value -> value.customerId } as KStream<Int, OrderCreatedEvent>)
                .join(customerTable, { orderIt, customer ->
                    OrderShippedEvent(orderIt.id, orderIt.productId, customer.name, customer.address)
                }, Joined.with(intSerde, orderCreatedSerde, customerSerde))
                .selectKey { _, value -> value.id }
    }

}
```

**application.yml**

```
spring:
  application:
    name: shipping-service
  cloud:
    stream:
      kafka:
        streams:
          binder:
            configuration:
              default:
                key:
                  serde: org.apache.kafka.common.serialization.Serdes$IntegerSerde
          bindings:
            input:
              consumer:
                valueSerde: io.confluent.kafka.streams.serdes.avro.GenericAvroSerde
      bindings:
        input:
          destination: customer
          contentType: application/*+avro
        order:
          destination: order
          contentType: application/*+avro
        output:
          destination: order
          contentType: application/*+avro
      schema-registry-client:
        endpoint: http://localhost:8081

server:
  port: 8086

```
But it is throwing the following exception:
```
org.springframework.messaging.converter.MessageConversionException: No schema can be inferred from type org.apache.avro.generic.GenericRecord and no schema has been explicitly configured.
	at org.springframework.cloud.stream.schema.avro.AvroSchemaServiceManagerImpl.getDatumReader(AvroSchemaServiceManagerImpl.java:147) ~[spring-cloud-stream-schema-2.2.0.BUILD-SNAPSHOT.jar:2.2.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.schema.avro.AvroSchemaServiceManagerImpl.readData(AvroSchemaServiceManagerImpl.java:164) ~[spring-cloud-stream-schema-2.2.0.BUILD-SNAPSHOT.jar:2.2.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.schema.avro.AbstractAvroMessageConverter.convertFromInternal(AbstractAvroMessageConverter.java:108) ~[spring-cloud-stream-schema-2.2.0.BUILD-SNAPSHOT.jar:2.2.0.BUILD-SNAPSHOT]
	at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:181) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.messaging.converter.AbstractMessageConverter.fromMessage(AbstractMessageConverter.java:172) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.messaging.converter.CompositeMessageConverter.fromMessage(CompositeMessageConverter.java:57) ~[spring-messaging-5.1.6.RELEASE.jar:5.1.6.RELEASE]
	at org.springframework.cloud.stream.binder.kafka.streams.KafkaStreamsMessageConversionDelegate.convertAndSetMessage(KafkaStreamsMessageConversionDelegate.java:218) ~[spring-cloud-stream-binder-kafka-streams-2.2.0.BUILD-20190426.192315-85.jar:2.2.0.BUILD-SNAPSHOT]
	at org.springframework.cloud.stream.binder.kafka.streams.KafkaStreamsMessageConversionDelegate.lambda$deserializeOnInbound$1(KafkaStreamsMessageConversionDelegate.java:146) ~[spring-cloud-stream-binder-kafka-streams-2.2.0.BUILD-20190426.192315-85.jar:2.2.0.BUILD-SNAPSHOT]
	at org.apache.kafka.streams.kstream.internals.KStreamBranch$KStreamBranchProcessor.process(KStreamBranch.java:45) ~[kafka-streams-2.0.1.jar:na]
```

Any advice about how to solve this?

**Comment by codependent** [comment]
Solved the exception setting:
```
spring:
  cloud:
      schema:
        avro:
          reader-schema: classpath:avro/order-created-event.avsc
```

**Comment by codependent** [comment]
@sobychacko If I'm not mistaken currently there's no way to use a GenericRecord without specifying a reader-schema, so there's no way to support multiple event types in the same topic with Avro serialization.

The key part is at `org.springframework.cloud.stream.schema.avro.AvroSchemaServiceManagerImpl`
```
	@Override
	public DatumReader<Object> getDatumReader(Class<?> type, Schema schema, Schema writerSchema) {
		DatumReader<Object> reader = null;
		if (SpecificRecord.class.isAssignableFrom(type)) {
			if (schema != null) {
				if (writerSchema != null) {
					reader = new SpecificDatumReader<>(writerSchema, schema);
				}
				else {
					reader = new SpecificDatumReader<>(schema);
				}
			}
			else {
				reader = new SpecificDatumReader(type);
				if (writerSchema != null) {
					reader.setSchema(writerSchema);
				}
			}
		}
		else if (GenericRecord.class.isAssignableFrom(type)) {
			if (schema != null) {
				if (writerSchema != null) {
					reader = new GenericDatumReader<>(writerSchema, schema);
				}
				else {
					reader = new GenericDatumReader<>(schema);
				}
			}
		}
		else {
			reader = new ReflectDatumReader(type);
			if (writerSchema != null) {
				reader.setSchema(writerSchema);
			}
		}
		if (reader == null) {
			throw new MessageConversionException("No schema can be inferred from type "
				+ type.getName() + " and no schema has been explicitly configured.");
		}
		return reader;
	}
```

With no specific configuration, not matter what we use, SpecificRecord or GenericRecord, that the schema (readerSchema) parameter is null. The difference is that in the case of SpecificRecord the null case asumes that schema is the writerSchema:

```
                if (SpecificRecord.class.isAssignableFrom(type)) {
			if (schema != null) {
				if (writerSchema != null) {
					reader = new SpecificDatumReader<>(writerSchema, schema);
				}
				else {
					reader = new SpecificDatumReader<>(schema);
				}
			}
			else {
				reader = new SpecificDatumReader(type);
				if (writerSchema != null) {
					reader.setSchema(writerSchema);
				}
			}
		}
```

However in the case of the GenericRecord there's not such an else block. I've tested locally with this modified implementation and it apparently it works:
```
         else if (GenericRecord.class.isAssignableFrom(type)) {
            if (schema != null) {
                if (writerSchema != null) {
                    reader = new GenericDatumReader<>(writerSchema, schema);
                }
                else {
                    reader = new GenericDatumReader<>(schema);
                }
            } else {
                if(writerSchema != null) {
                    reader = new GenericDatumReader(writerSchema);
                }
            }
        }
```

Does this make sense? Am I missing something?

**Comment by sobychacko** [comment]
@codependent My apologies for the delay in getting back to you. What you said above about the `GenericRecord` makes sense to me. Do you want to send a PR to core spring cloud stream with a fix for that? I am reviewing this PR right now. Please let me know how you want to proceed. Thank you!

**Comment by codependent** [comment]
Hi @sobychacko, no worries for the delay :-) I've just [submitted a PR](https://github.com/spring-cloud/spring-cloud-stream/pull/1727) with the proposed modification.

If it is accepted I would go back to this sample to finish it off, leaving it fully functional.

**Comment by sobychacko** [comment]
@codependent The PR in core is now merged. Please go ahead and make the amends on this PR. Thank you!

**Comment by codependent** [comment]
@sobychacko I've made the changes you suggested previously and verified that everything works with the changes introduced in the `AvroSchemaServiceManagerImpl`. Could you have a look a it? Thanks!

**Comment by sobychacko** [comment]
@codependent I am trying to do a build from the root of the application and getting this error. Do we need to add some build config (that may be available by default on your local environment)?

```
./mvnw clean package
/Users/sobychacko/spring/spring-cloud-stream-samples/kafka-e2e-kotlin-sample
[INFO] Scanning for projects...
[ERROR] [ERROR] Some problems were encountered while processing the POMs:
[ERROR] Non-resolvable import POM: Failure to find org.jetbrains.kotlin:kotlin-bom:pom:1.2.71 in http://packages.confluent.io/maven/ was cached in the local repository, resolution will not be reattempted until the update interval of confluent has elapsed or updates are forced @ org.springframework.boot:spring-boot-dependencies:2.2.0.BUILD-SNAPSHOT, /Users/sobychacko/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.2.0.BUILD-SNAPSHOT/spring-boot-dependencies-2.2.0.BUILD-SNAPSHOT.pom, line 2596, column 19
[ERROR] 'dependencies.dependency.version' for org.jetbrains.kotlin:kotlin-reflect:jar is missing. @ line 68, column 21
[ERROR] 'dependencies.dependency.version' for org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar is missing. @ line 72, column 21
[ERROR] Non-resolvable import POM: Failure to find org.jetbrains.kotlin:kotlin-bom:pom:1.2.71 in http://packages.confluent.io/maven/ was cached in the local repository, resolution will not be reattempted until the update interval of confluent has elapsed or updates are forced @ org.springframework.boot:spring-boot-dependencies:2.2.0.BUILD-SNAPSHOT, /Users/sobychacko/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.2.0.BUILD-SNAPSHOT/spring-boot-dependencies-2.2.0.BUILD-SNAPSHOT.pom, line 2596, column 19
[ERROR] 'dependencies.dependency.version' for org.jetbrains.kotlin:kotlin-reflect:jar is missing. @ line 68, column 21
[ERROR] 'dependencies.dependency.version' for org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar is missing. @ line 72, column 21
[ERROR] Non-resolvable import POM: Failure to find org.jetbrains.kotlin:kotlin-bom:pom:1.2.71 in http://packages.confluent.io/maven/ was cached in the local repository, resolution will not be reattempted until the update interval of confluent has elapsed or updates are forced @ org.springframework.boot:spring-boot-dependencies:2.2.0.BUILD-SNAPSHOT, /Users/sobychacko/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.2.0.BUILD-SNAPSHOT/spring-boot-dependencies-2.2.0.BUILD-SNAPSHOT.pom, line 2596, column 19
[ERROR] 'dependencies.dependency.version' for org.jetbrains.kotlin:kotlin-reflect:jar is missing. @ line 68, column 21
[ERROR] 'dependencies.dependency.version' for org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar is missing. @ line 72, column 21
 @
[ERROR] The build could not read 3 projects -> [Help 1]
[ERROR]
[ERROR]   The project io.spring.cloud.stream.sample:customer-service:0.0.1-SNAPSHOT (/Users/sobychacko/spring/spring-cloud-stream-samples/kafka-e2e-kotlin-sample/customer-service/pom.xml) has 3 errors
[ERROR]     Non-resolvable import POM: Failure to find org.jetbrains.kotlin:kotlin-bom:pom:1.2.71 in http://packages.confluent.io/maven/ was cached in the local repository, resolution will not be reattempted until the update interval of confluent has elapsed or updates are forced @ org.springframework.boot:spring-boot-dependencies:2.2.0.BUILD-SNAPSHOT, /Users/sobychacko/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.2.0.BUILD-SNAPSHOT/spring-boot-dependencies-2.2.0.BUILD-SNAPSHOT.pom, line 2596, column 19 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.jetbrains.kotlin:kotlin-reflect:jar is missing. @ line 68, column 21
[ERROR]     'dependencies.dependency.version' for org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar is missing. @ line 72, column 21
[ERROR]
[ERROR]   The project io.spring.cloud.stream.sample:order-service:0.0.1-SNAPSHOT (/Users/sobychacko/spring/spring-cloud-stream-samples/kafka-e2e-kotlin-sample/order-service/pom.xml) has 3 errors
[ERROR]     Non-resolvable import POM: Failure to find org.jetbrains.kotlin:kotlin-bom:pom:1.2.71 in http://packages.confluent.io/maven/ was cached in the local repository, resolution will not be reattempted until the update interval of confluent has elapsed or updates are forced @ org.springframework.boot:spring-boot-dependencies:2.2.0.BUILD-SNAPSHOT, /Users/sobychacko/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.2.0.BUILD-SNAPSHOT/spring-boot-dependencies-2.2.0.BUILD-SNAPSHOT.pom, line 2596, column 19 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.jetbrains.kotlin:kotlin-reflect:jar is missing. @ line 68, column 21
[ERROR]     'dependencies.dependency.version' for org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar is missing. @ line 72, column 21
[ERROR]
[ERROR]   The project io.spring.cloud.stream.sample:shipping-service:0.0.1-SNAPSHOT (/Users/sobychacko/spring/spring-cloud-stream-samples/kafka-e2e-kotlin-sample/shipping-service/pom.xml) has 3 errors
[ERROR]     Non-resolvable import POM: Failure to find org.jetbrains.kotlin:kotlin-bom:pom:1.2.71 in http://packages.confluent.io/maven/ was cached in the local repository, resolution will not be reattempted until the update interval of confluent has elapsed or updates are forced @ org.springframework.boot:spring-boot-dependencies:2.2.0.BUILD-SNAPSHOT, /Users/sobychacko/.m2/repository/org/springframework/boot/spring-boot-dependencies/2.2.0.BUILD-SNAPSHOT/spring-boot-dependencies-2.2.0.BUILD-SNAPSHOT.pom, line 2596, column 19 -> [Help 2]
[ERROR]     'dependencies.dependency.version' for org.jetbrains.kotlin:kotlin-reflect:jar is missing. @ line 68, column 21
[ERROR]     'dependencies.dependency.version' for org.jetbrains.kotlin:kotlin-stdlib-jdk8:jar is missing. @ line 72, column 21
[ERROR]
[ERROR] To see the full stack trace of the errors, re-run Maven with the -e switch.
[ERROR] Re-run Maven using the -X switch to enable full debug logging.
[ERROR]
[ERROR] For more information about the errors and possible solutions, please read the following articles:
[ERROR] [Help 1] http://cwiki.apache.org/confluence/display/MAVEN/ProjectBuildingException
[ERROR] [Help 2] http://cwiki.apache.org/confluence/display/MAVEN/UnresolvableModelException
```

**Comment by codependent** [comment]
@sobychacko That's weird I removed my full local maven repository and the dependency was correctly resolved again. Anyway I upgraded to [Kotlin 1.3.31](http://central.maven.org/maven2/org/jetbrains/kotlin/kotlin-bom/) which shouldn't give any problem. Could you try again?

**Comment by sobychacko** [comment]
@codependent It is good now. This PR is now merged upstream. This is a great addition to the samples. Thank you very much for contributing this. More PR's to the core project and the samples are welcomed!

**Pull request closed without merging**
